ALTER TABLE "Article" ADD COLUMN "categorySlug" TEXT NOT NULL DEFAULT 'competition-result';
ALTER TABLE "Article" ALTER COLUMN "category" SET DEFAULT '대회 결과';
ALTER TABLE "Article" ADD COLUMN "tag" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Article" ADD COLUMN "readMinutes" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Article" ADD COLUMN "posterTheme" TEXT NOT NULL DEFAULT 'navy';
ALTER TABLE "Article" ADD COLUMN "posterFigure" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Article" ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Article" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Article" ADD COLUMN "bodyBlocksJson" TEXT NOT NULL DEFAULT '[]';

UPDATE "Article"
SET
  "category" = '대회 결과',
  "categorySlug" = 'competition-result',
  "tag" = '현장 리포트',
  "readMinutes" = 7,
  "posterTheme" = 'navy',
  "posterFigure" = 0,
  "isFeatured" = false,
  "sortOrder" = 1
WHERE "slug" = '2026-world-of-monsterzym-korea-pro-results';

WITH seed AS (
  SELECT *
  FROM jsonb_to_recordset($articles$
[
  {
    "id": "article_korea-classic-2026-results",
    "slug": "korea-classic-2026-results",
    "title": "2026 IFBB 코리아 클래식 결과 총정리",
    "excerpt": "맨즈 피지크부터 비키니까지 — 전 체급 입상자와 무대를 가른 결정적 디테일을 정리했습니다.",
    "category": "대회 결과",
    "category_slug": "competition-result",
    "tag": "현장 리포트",
    "status": "published",
    "language": "ko",
    "author_name": "편집팀",
    "read_minutes": 6,
    "poster_theme": "navy",
    "poster_figure": 0,
    "is_featured": true,
    "sort_order": 10,
    "body_blocks": [
      { "t": "p", "x": "올해 코리아 클래식은 역대 가장 많은 참가 인원을 기록하며 막을 내렸습니다. 종목별로 컨디셔닝 수준이 전반적으로 올라왔고, 상위권은 사실상 무대 위 디테일에서 갈렸습니다. 이번 리포트에서는 주요 체급의 흐름과 심사 포인트를 정리합니다." },
      { "t": "h", "x": "맨즈 피지크 — 라인보다 균형" },
      { "t": "p", "x": "상위 입상자들의 공통점은 압도적인 사이즈가 아니라 어깨-허리 비율과 무대 위 안정감이었습니다. 비교 심사에서 V 테이퍼를 끝까지 유지한 선수가 점수를 가져갔고, 막판 라인업에서 호흡이 흔들린 경우 순위가 뒤집혔습니다." },
      { "t": "quote", "x": "\"같은 조건이면, 마지막 30초를 버티는 쪽이 이깁니다.\"" },
      { "t": "h", "x": "비키니 — 워킹과 표현력" },
      { "t": "p", "x": "비키니 부문은 컨디션 격차가 크지 않아 워킹의 완성도와 표현력이 결정적이었습니다. 쿼터 턴 전환에서 시선 처리와 발 위치를 정리한 선수들이 꾸준히 콜백을 받았습니다." },
      { "t": "h", "x": "총평" },
      { "t": "p", "x": "전반적으로 '무대를 끝까지 컨트롤하는 능력'이 올해의 키워드였습니다. 다음 시즌을 준비한다면 피지컬만큼 무대 위 루틴을 반복 훈련하는 것이 중요해 보입니다. 세부 순위와 체급별 콜백 기록은 각 단체 공식 공지를 확인하세요." }
    ],
    "tags": ["대회 결과", "현장 리포트"],
    "published_at": "2026-05-24T00:00:00+09:00"
  },
  {
    "id": "article_peak-week-checklist",
    "slug": "peak-week-checklist",
    "title": "피크위크 7일: 막판 컨디셔닝 체크리스트",
    "excerpt": "수분·탄수·소금 타이밍을 무대 당일까지 단계별로. 흔한 실수와 안전한 조정 폭.",
    "category": "트레이닝",
    "category_slug": "training",
    "tag": "프로그램",
    "status": "published",
    "language": "ko",
    "author_name": "코칭 데스크",
    "read_minutes": 8,
    "poster_theme": "amber",
    "poster_figure": 1,
    "is_featured": false,
    "sort_order": 11,
    "body_blocks": [
      { "t": "p", "x": "피크위크는 새로운 것을 시도하는 주간이 아니라, 이미 만들어 둔 컨디션을 무대 위에서 최상으로 보여주기 위한 미세 조정 기간입니다. 핵심 원칙은 단순합니다 — 급격한 변화를 피하고, 몸의 반응을 보면서 폭을 좁혀가는 것." },
      { "t": "h", "x": "수분: 줄이기보다 흐름 유지" },
      { "t": "p", "x": "무리한 수분 제한은 오히려 근육을 평평하게 만들고 컨디션을 무너뜨립니다. 평소 섭취량을 유지하다가 막판에 자연스럽게 줄이는 방식이 안전합니다." },
      { "t": "list", "items": ["D-7 ~ D-3: 평소 수분량 유지, 나트륨 일정하게", "D-2: 몸 상태를 보며 소폭 조정", "D-1: 컨디션 확인 후 미세 조정 — 무리한 컷 금지"] },
      { "t": "h", "x": "탄수: 채움은 점진적으로" },
      { "t": "p", "x": "카본 로딩은 양보다 타이밍과 반응 관찰이 중요합니다. 한 번에 몰아넣기보다 며칠에 걸쳐 나누고, 거울로 충전 정도를 확인하며 조절하세요." },
      { "t": "quote", "x": "\"피크위크의 목표는 새 기록이 아니라, 무너지지 않는 것입니다.\"" },
      { "t": "h", "x": "안전 수칙" },
      { "t": "p", "x": "어지럼·경련·과도한 탈수 신호가 오면 즉시 계획을 멈추고 회복을 우선하세요. 모든 수치는 개인차가 크므로, 코치·전문가와 함께 본인 데이터를 기준으로 조정하는 것이 가장 안전합니다." }
    ],
    "tags": ["트레이닝", "프로그램"],
    "published_at": "2026-05-20T00:00:00+09:00"
  },
  {
    "id": "article_diet-plateau",
    "slug": "diet-plateau",
    "title": "다이어트 정체기, 칼로리부터 줄여야 할까",
    "excerpt": "활동량·리피드·트레이닝 볼륨을 먼저 점검하는 순서. 무작정 줄이기 전에 볼 것들.",
    "category": "영양",
    "category_slug": "nutrition",
    "tag": "가이드",
    "status": "published",
    "language": "ko",
    "author_name": "영양 데스크",
    "read_minutes": 7,
    "poster_theme": "sage",
    "poster_figure": 2,
    "is_featured": false,
    "sort_order": 12,
    "body_blocks": [
      { "t": "p", "x": "체중이 2~3주째 멈췄다고 곧장 칼로리를 깎는 것은 가장 흔한 실수입니다. 정체기에는 줄이기 전에 점검할 항목이 더 많습니다." },
      { "t": "h", "x": "먼저 확인할 것들" },
      { "t": "list", "items": ["일상 활동량(NEAT)이 줄지 않았는가", "수면과 스트레스가 회복을 방해하고 있지 않은가", "트레이닝 볼륨·강도가 유지되고 있는가", "기록이 실제 섭취량과 일치하는가"] },
      { "t": "p", "x": "이 네 가지에서 새는 부분을 막으면, 칼로리를 더 깎지 않고도 다시 움직이는 경우가 많습니다." },
      { "t": "h", "x": "그래도 멈춰 있다면" },
      { "t": "p", "x": "리피드나 다이어트 브레이크로 대사와 호르몬을 잠시 회복시키는 편이, 무작정 더 줄이는 것보다 장기적으로 유리할 수 있습니다. 핵심은 '얼마나 빨리'가 아니라 '얼마나 지속 가능하게'입니다." }
    ],
    "tags": ["영양", "가이드"],
    "published_at": "2026-05-18T00:00:00+09:00"
  },
  {
    "id": "article_first-pro-card",
    "slug": "first-pro-card",
    "title": "첫 프로카드까지 3년, 무대 뒤의 기록",
    "excerpt": "루키 무대에서 프로 퀄리파이어까지. 시즌을 설계한 방식과 번아웃을 넘긴 이야기.",
    "category": "인터뷰",
    "category_slug": "interview",
    "tag": "선수",
    "status": "published",
    "language": "ko",
    "author_name": "편집팀",
    "read_minutes": 10,
    "poster_theme": "rose",
    "poster_figure": 4,
    "is_featured": false,
    "sort_order": 13,
    "body_blocks": [
      { "t": "p", "x": "한 선수가 루키 무대에 처음 선 뒤 프로카드를 받기까지 걸린 시간은 3년이었습니다. 화려한 결과 뒤에는 시즌을 어떻게 쪼개고, 무엇을 포기했는지에 대한 기록이 있었습니다." },
      { "t": "h", "x": "첫 시즌 — 완성보다 경험" },
      { "t": "p", "x": "\"첫해에는 입상보다 무대 자체에 익숙해지는 걸 목표로 했어요. 조명, 대기 시간, 비교 심사의 압박 — 영상으로는 절대 배울 수 없는 것들이었죠.\"" },
      { "t": "quote", "x": "\"이기려고만 했다면 1년 만에 그만뒀을 거예요.\"" },
      { "t": "h", "x": "번아웃을 넘긴 방법" },
      { "t": "p", "x": "두 번째 시즌 중반, 정체와 피로가 겹치며 무너질 뻔했다고 합니다. 그때 택한 건 더 강한 훈련이 아니라 의도적인 휴식과 목표 재설정이었습니다." },
      { "t": "h", "x": "다음을 준비하는 사람에게" },
      { "t": "p", "x": "\"조급함이 가장 큰 적이에요. 시즌을 길게 보고, 오프시즌을 잘 보내는 사람이 결국 무대에 오래 남더라고요.\"" }
    ],
    "tags": ["인터뷰", "선수"],
    "published_at": "2026-05-15T00:00:00+09:00"
  },
  {
    "id": "article_back-detail-rows",
    "slug": "back-detail-rows",
    "title": "백 디테일을 살리는 로우 4가지",
    "excerpt": "광배·하부 승모·척추기립근을 분리해 자극하는 컨트롤 큐와 흔한 보상 동작 교정.",
    "category": "트레이닝",
    "category_slug": "training",
    "tag": "테크닉",
    "status": "published",
    "language": "ko",
    "author_name": "코칭 데스크",
    "read_minutes": 6,
    "poster_theme": "deep",
    "poster_figure": 5,
    "is_featured": false,
    "sort_order": 14,
    "body_blocks": [
      { "t": "p", "x": "넓은 등은 사이즈만으로 완성되지 않습니다. 부위별로 분리해 자극하고, 보상 동작을 줄여야 무대 위에서 '디테일'로 보입니다." },
      { "t": "h", "x": "1. 광배 — 팔꿈치로 당기기" },
      { "t": "p", "x": "손이 아니라 팔꿈치를 주머니 쪽으로 당긴다는 느낌으로. 가동 범위 끝에서 1초 멈추면 수축이 훨씬 선명해집니다." },
      { "t": "h", "x": "2. 하부 승모 — 견갑 하강" },
      { "t": "p", "x": "당기기 전에 견갑을 아래로 정리하면 승모 상부의 개입을 줄이고 가운데 등의 두께를 만들 수 있습니다." },
      { "t": "h", "x": "3·4. 기립근과 마무리" },
      { "t": "p", "x": "데드 계열로 기립근 두께를 쌓되, 허리 피로가 누적되지 않도록 볼륨을 관리하세요. 마지막엔 가벼운 펌핑 세트로 디테일을 끌어올립니다." },
      { "t": "quote", "x": "\"무게보다 어디에 들어가는지가 등을 만듭니다.\"" }
    ],
    "tags": ["트레이닝", "테크닉"],
    "published_at": "2026-05-12T00:00:00+09:00"
  },
  {
    "id": "article_olympia-qualify-status",
    "slug": "olympia-qualify-status",
    "title": "올림피아로 가는 길: 퀄리파이 현황",
    "excerpt": "현재까지 확정된 출전권과 남은 프로쇼 일정. 주목할 매치업을 미리 짚어봤습니다.",
    "category": "대회 결과",
    "category_slug": "competition-result",
    "tag": "프리뷰",
    "status": "published",
    "language": "ko",
    "author_name": "편집팀",
    "read_minutes": 5,
    "poster_theme": "lime",
    "poster_figure": 3,
    "is_featured": false,
    "sort_order": 15,
    "body_blocks": [
      { "t": "p", "x": "시즌이 중반을 지나며 올림피아 출전권 구도가 조금씩 윤곽을 드러내고 있습니다. 확정 자격을 얻은 선수와, 남은 프로쇼에서 마지막 티켓을 노리는 선수들을 정리했습니다." },
      { "t": "h", "x": "이미 확정된 출전권" },
      { "t": "p", "x": "시즌 초반 주요 프로쇼 우승자들은 일찌감치 자격을 확보했습니다. 이들은 무대 빈도를 줄이고 컨디션 빌드업에 집중하는 분위기입니다." },
      { "t": "h", "x": "남은 변수" },
      { "t": "p", "x": "포인트 랭킹으로 막판 진입을 노리는 그룹의 경쟁이 가장 치열합니다. 남은 일정에서 한두 번의 결과가 순위를 통째로 흔들 수 있습니다." },
      { "t": "p", "x": "구체적인 출전권·랭킹 수치는 변동이 잦으므로, 최종 확정은 공식 발표를 기준으로 확인하시기 바랍니다." }
    ],
    "tags": ["대회 결과", "프리뷰"],
    "published_at": "2026-05-09T00:00:00+09:00"
  },
  {
    "id": "article_protein-timing",
    "slug": "protein-timing",
    "title": "단백질 타이밍, 정말 중요할까",
    "excerpt": "총량이 먼저다 — 그다음에 의미가 생기는 분배. 근거와 실전 사이의 균형 찾기.",
    "category": "영양",
    "category_slug": "nutrition",
    "tag": "기초",
    "status": "published",
    "language": "ko",
    "author_name": "영양 데스크",
    "read_minutes": 7,
    "poster_theme": "navy",
    "poster_figure": 2,
    "is_featured": false,
    "sort_order": 16,
    "body_blocks": [
      { "t": "p", "x": "'운동 직후 30분'이라는 말은 오래 회자됐지만, 실제로 더 중요한 건 하루 총 단백질 섭취량입니다. 타이밍은 그 위에서 의미가 생깁니다." },
      { "t": "h", "x": "우선순위는 총량" },
      { "t": "p", "x": "목표 체중 기준으로 충분한 단백질을 매일 채우는 것이 1순위입니다. 이게 흔들리면 타이밍을 아무리 맞춰도 효과는 제한적입니다." },
      { "t": "h", "x": "그다음이 분배" },
      { "t": "p", "x": "총량이 확보됐다면, 하루 3~5회로 고르게 나누는 편이 한 끼에 몰아넣는 것보다 합리적입니다. 운동 전후로 한 끼를 배치하면 자연스럽게 '타이밍'도 챙겨집니다." },
      { "t": "quote", "x": "\"기본을 지키면, 디테일이 비로소 일을 합니다.\"" }
    ],
    "tags": ["영양", "기초"],
    "published_at": "2026-05-06T00:00:00+09:00"
  },
  {
    "id": "article_post-show-rebound",
    "slug": "post-show-rebound",
    "title": "무대 후 리바운드, 어떻게 관리할까",
    "excerpt": "급격한 보충을 피하고 컨디션을 되돌리는 2주 플랜. 멘탈 관리까지 함께.",
    "category": "트레이닝",
    "category_slug": "training",
    "tag": "회복",
    "status": "published",
    "language": "ko",
    "author_name": "코칭 데스크",
    "read_minutes": 8,
    "poster_theme": "amber",
    "poster_figure": 1,
    "is_featured": false,
    "sort_order": 17,
    "body_blocks": [
      { "t": "p", "x": "무대가 끝난 직후의 폭식은 가장 흔하면서도 후유증이 큰 실수입니다. 리바운드는 막는 게 아니라 '관리'하는 대상입니다." },
      { "t": "h", "x": "첫 3일 — 천천히" },
      { "t": "p", "x": "극단적으로 빠진 상태에서 갑자기 많은 음식을 넣으면 소화 불편과 급격한 수분 저류가 옵니다. 평소 식단 수준으로 부드럽게 복귀하세요." },
      { "t": "h", "x": "남은 기간 — 리버스" },
      { "t": "p", "x": "칼로리를 단계적으로 올리는 리버스 다이어트로 대사를 회복시키면, 오프시즌을 더 건강하게 시작할 수 있습니다." },
      { "t": "h", "x": "멘탈도 회복 대상" },
      { "t": "p", "x": "무대 후 공허함은 자연스러운 반응입니다. 다음 목표를 너무 빨리 세우기보다, 잠시 쉬며 시즌을 돌아보는 시간이 필요합니다." }
    ],
    "tags": ["트레이닝", "회복"],
    "published_at": "2026-05-03T00:00:00+09:00"
  },
  {
    "id": "article_judges-stage-presence",
    "slug": "judges-stage-presence",
    "title": "심사위원이 본 '무대 장악력'이란",
    "excerpt": "같은 조건이면 무엇이 점수를 가를까. 포징·표정·워킹에 대한 현장의 시선.",
    "category": "인터뷰",
    "category_slug": "interview",
    "tag": "심사위원",
    "status": "published",
    "language": "ko",
    "author_name": "편집팀",
    "read_minutes": 9,
    "poster_theme": "sage",
    "poster_figure": 4,
    "is_featured": false,
    "sort_order": 18,
    "body_blocks": [
      { "t": "p", "x": "컨디션이 비슷한 선수들 사이에서 점수를 가르는 건 결국 '무대 장악력'이라는 말을 자주 듣습니다. 한 심사위원에게 그 실체를 물었습니다." },
      { "t": "h", "x": "장악력은 자신감에서" },
      { "t": "p", "x": "\"긴장한 게 보이면 아무리 좋은 몸도 작아 보여요. 반대로 무대를 즐기는 선수는 같은 조건에서 더 커 보이죠.\"" },
      { "t": "quote", "x": "\"심사위원은 몸만 보지 않습니다. 그 몸을 어떻게 보여주는지를 봅니다.\"" },
      { "t": "h", "x": "디테일이 쌓여 인상이 된다" },
      { "t": "p", "x": "시선 처리, 전환 동작의 매끄러움, 라인업에서의 자세 유지 — 작은 디테일이 모여 전체 인상을 만든다는 설명입니다. 결국 무대 위 모든 순간이 평가 대상이라는 의미입니다." }
    ],
    "tags": ["인터뷰", "심사위원"],
    "published_at": "2026-04-29T00:00:00+09:00"
  },
  {
    "id": "article_quarter-turn",
    "slug": "quarter-turn",
    "title": "쿼터 턴, 1cm가 만드는 차이",
    "excerpt": "정면-측면 전환에서 라인을 끊지 않는 발·골반·시선의 순서를 분해했습니다.",
    "category": "트레이닝",
    "category_slug": "training",
    "tag": "포징",
    "status": "published",
    "language": "ko",
    "author_name": "코칭 데스크",
    "read_minutes": 5,
    "poster_theme": "rose",
    "poster_figure": 0,
    "is_featured": false,
    "sort_order": 19,
    "body_blocks": [
      { "t": "p", "x": "쿼터 턴은 단순히 90도 도는 동작이 아니라, 라인을 끊지 않고 다음 포즈로 넘어가는 연결의 기술입니다. 순서만 정리해도 인상이 크게 달라집니다." },
      { "t": "h", "x": "발 → 골반 → 상체 → 시선" },
      { "t": "p", "x": "한 번에 몸 전체를 돌리면 라인이 무너집니다. 발 위치를 먼저 잡고 골반, 상체, 마지막으로 시선을 정리하면 전환 내내 긴장감이 유지됩니다." },
      { "t": "h", "x": "거울 앞 반복" },
      { "t": "p", "x": "발 간격 1cm, 시선 각도의 미세한 차이가 사진과 무대에서 전혀 다른 결과를 만듭니다. 결국 답은 반복 연습입니다." },
      { "t": "quote", "x": "\"포징은 정적인 게 아니라, 멈춰 있는 동작입니다.\"" }
    ],
    "tags": ["트레이닝", "포징"],
    "published_at": "2026-04-25T00:00:00+09:00"
  },
  {
    "id": "article_national-festival-report",
    "slug": "national-festival-report",
    "title": "전국체전 보디빌딩, 시·도 대표 성적표",
    "excerpt": "주목할 신인과 베테랑의 무대. 종목별 하이라이트와 다음 시즌 관전 포인트.",
    "category": "대회 결과",
    "category_slug": "competition-result",
    "tag": "현장 리포트",
    "status": "published",
    "language": "ko",
    "author_name": "편집팀",
    "read_minutes": 6,
    "poster_theme": "lime",
    "poster_figure": 3,
    "is_featured": false,
    "sort_order": 20,
    "body_blocks": [
      { "t": "p", "x": "전국체전은 시·도 대표라는 상징성 때문에 매년 분위기가 남다릅니다. 올해도 신인의 약진과 베테랑의 노련함이 교차하는 무대가 펼쳐졌습니다." },
      { "t": "h", "x": "신인의 약진" },
      { "t": "p", "x": "처음 대표로 나선 선수들이 예상을 뛰어넘는 컨디션으로 콜백을 받으며, 다음 시즌을 기대하게 했습니다." },
      { "t": "h", "x": "베테랑의 무게" },
      { "t": "p", "x": "오랜 경험에서 나오는 무대 운영은 여전히 강력했습니다. 결정적인 비교 심사에서 흔들리지 않는 모습이 인상적이었습니다." },
      { "t": "p", "x": "종목별 세부 순위와 대표 명단은 대한체육회·관련 단체 공식 자료를 확인하시기 바랍니다." }
    ],
    "tags": ["대회 결과", "현장 리포트"],
    "published_at": "2026-04-21T00:00:00+09:00"
  },
  {
    "id": "article_eating-out-prep",
    "slug": "eating-out-prep",
    "title": "외식하면서 시즌 준비하는 법",
    "excerpt": "메뉴 선택의 우선순위와 매크로 어림 계산. 완벽 대신 지속 가능한 선택.",
    "category": "영양",
    "category_slug": "nutrition",
    "tag": "실전",
    "status": "published",
    "language": "ko",
    "author_name": "영양 데스크",
    "read_minutes": 7,
    "poster_theme": "deep",
    "poster_figure": 5,
    "is_featured": false,
    "sort_order": 21,
    "body_blocks": [
      { "t": "p", "x": "모든 끼니를 직접 준비할 수 없는 게 현실입니다. 외식을 피하기보다, 외식에서도 시즌을 망치지 않는 선택법을 익히는 편이 지속 가능합니다." },
      { "t": "h", "x": "단백질을 먼저 고른다" },
      { "t": "p", "x": "메뉴를 볼 때 단백질 소스를 가장 먼저 정하세요. 구이·찜처럼 조리법이 단순한 쪽이 칼로리 예측이 쉽습니다." },
      { "t": "h", "x": "완벽 대신 어림" },
      { "t": "list", "items": ["소스·튀김옷은 칼로리의 가장 큰 변수 — 가능하면 덜어내기", "탄수는 양을 눈대중으로 절반만", "한 끼가 어긋나도 하루 총량으로 맞추기"] },
      { "t": "quote", "x": "\"완벽한 하루보다, 지킬 수 있는 한 주가 이깁니다.\"" }
    ],
    "tags": ["영양", "실전"],
    "published_at": "2026-04-17T00:00:00+09:00"
  }
]
$articles$::jsonb) AS x(
    id TEXT,
    slug TEXT,
    title TEXT,
    excerpt TEXT,
    category TEXT,
    category_slug TEXT,
    tag TEXT,
    status TEXT,
    language TEXT,
    author_name TEXT,
    read_minutes INTEGER,
    poster_theme TEXT,
    poster_figure INTEGER,
    is_featured BOOLEAN,
    sort_order INTEGER,
    body_blocks JSONB,
    tags JSONB,
    published_at TIMESTAMPTZ
  )
)
INSERT INTO "Article" (
  "id",
  "slug",
  "title",
  "excerpt",
  "category",
  "categorySlug",
  "tag",
  "status",
  "language",
  "authorName",
  "readMinutes",
  "posterTheme",
  "posterFigure",
  "isFeatured",
  "sortOrder",
  "bodyMarkdown",
  "bodyBlocksJson",
  "sourceUrlsJson",
  "tagsJson",
  "publishedAt",
  "updatedAt"
)
SELECT
  id,
  slug,
  title,
  excerpt,
  category,
  category_slug,
  tag,
  status,
  language,
  author_name,
  read_minutes,
  poster_theme,
  poster_figure,
  is_featured,
  sort_order,
  excerpt,
  body_blocks::text,
  '[]',
  tags::text,
  published_at,
  CURRENT_TIMESTAMP
FROM seed
ON CONFLICT ("slug") DO UPDATE SET
  "title" = EXCLUDED."title",
  "excerpt" = EXCLUDED."excerpt",
  "category" = EXCLUDED."category",
  "categorySlug" = EXCLUDED."categorySlug",
  "tag" = EXCLUDED."tag",
  "status" = EXCLUDED."status",
  "language" = EXCLUDED."language",
  "authorName" = EXCLUDED."authorName",
  "readMinutes" = EXCLUDED."readMinutes",
  "posterTheme" = EXCLUDED."posterTheme",
  "posterFigure" = EXCLUDED."posterFigure",
  "isFeatured" = EXCLUDED."isFeatured",
  "sortOrder" = EXCLUDED."sortOrder",
  "bodyBlocksJson" = EXCLUDED."bodyBlocksJson",
  "sourceUrlsJson" = EXCLUDED."sourceUrlsJson",
  "tagsJson" = EXCLUDED."tagsJson",
  "publishedAt" = EXCLUDED."publishedAt",
  "updatedAt" = CURRENT_TIMESTAMP;

CREATE INDEX "Article_categorySlug_idx" ON "Article"("categorySlug");
CREATE INDEX "Article_isFeatured_publishedAt_idx" ON "Article"("isFeatured", "publishedAt");
