import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BookOpen,
  Bookmark,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Home,
  Paperclip,
  LayoutGrid,
  List,
  MapPin,
  MessageCircle,
  Moon,
  Search,
  Share2,
  Sun,
  Tag,
  Trash2,
  X,
} from "lucide-react";

const iconProps = {
  "aria-hidden": true,
  focusable: false,
  strokeWidth: 2,
} as const;

export const Icons = {
  home: <Home {...iconProps} />,
  search: <Search {...iconProps} />,
  bookmark: <Bookmark {...iconProps} />,
  bookmarkFilled: <Bookmark {...iconProps} fill="currentColor" />,
  book: <BookOpen {...iconProps} />,
  arrow: <ArrowRight {...iconProps} />,
  arrowDown: <ArrowDown {...iconProps} />,
  arrowLeft: <ArrowLeft {...iconProps} />,
  sort: <ArrowUpDown {...iconProps} />,
  chevronDown: <ChevronDown {...iconProps} />,
  chevronUp: <ChevronUp {...iconProps} />,
  close: <X {...iconProps} />,
  list: <List {...iconProps} />,
  grid: <LayoutGrid {...iconProps} />,
  contact: <MessageCircle {...iconProps} />,
  cal: <CalendarDays {...iconProps} />,
  pin: <MapPin {...iconProps} />,
  tag: <Tag {...iconProps} />,
  check: <Check {...iconProps} strokeWidth={3} />,
  share: <Share2 {...iconProps} />,
  ext: <ExternalLink {...iconProps} />,
  paperclip: <Paperclip {...iconProps} />,
  trash: <Trash2 {...iconProps} />,
  sun: <Sun {...iconProps} />,
  moon: <Moon {...iconProps} />,
};
